# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via Dico, hho1993@gmail.com, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via .
title: 사이트제목
email: 이메일
description: 사이트 설명

baseurl: "" # the subpath of your site, e.g. /blog
url: "github 주소" # the base hostname & protocol for your site
twitter_username: 트위터 네임
github_username:  github 네임

# Build settings
markdown: kramdown
theme: minima